name: Terraform Plan

on:
  push:
    paths:
      - "terraform/**"
      - ".github/workflows/terraform.yml"

  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/terraform.yml"

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: arn:aws:iam::149957954264:role/EnterpriseSecurityLab-GitHubOIDC
          aws-region: us-east-1

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.8

      - name: Terraform Version
        uses: hashicorp/setup-terraform@v4
        with:
           terraform_version: 1.15.8

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Format Check
        working-directory: terraform
        run: terraform fmt -check -diff -no-color

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan
