name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - "terraform/**"
      - ".github/workflows/terraform-apply.yml"

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    environment:
     name: terraform-deploy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
         debug-github-oidc-claims
      - name: Inspect GitHub OIDC claims
        shell: bash
        run: |
          OIDC_TOKEN=$(curl -sS \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" \
            | jq -r '.value')

          PAYLOAD=$(echo "$OIDC_TOKEN" | cut -d '.' -f2 | tr '_-' '/+')

          echo "$PAYLOAD" | base64 --decode 2>/dev/null | jq '{
            sub,
            aud,
            repository,
            repository_id,
            repository_owner,
            repository_owner_id,
            environment,
            ref
          }'
          - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: arn:aws:iam::149957954264:role/EnterpriseSecurityLab-TerraformDeploy
          aws-region: us-east-1

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.15.8

      - name: Terraform Version
        run: terraform version

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve
